DEPLOYMENT:
    ENV: test
    NAMESPACE: test
    CONFIG_FILES:
        - "src/main/resources/config/location-service.default.yaml"
        - "src/main/resources/config/location-service.test.yaml"

APP:
    REPLICA: 6
    HPA:
      ENABLED: 0
      MIN_REPLICA: 3
      MAX_REPLICA: 6
      CPU_UTILIZATION: 65
      MEMORY_UTILIZATION: 80
    CONTAINER:
      MEMORY:
        REQUEST: 1Gi
        LIMIT: 1536Mi
      CPU:
        REQUEST: 0.5
        LIMIT: 1
    ENVIRONMENT:
      - KEY: logs.Dir
        VALUE: "/apps/logs/test/location-service/"
